# Dockerfile.rails
FROM ruby:3.1.2 AS rails-toolbox

# Default directory
ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

# install rails
RUN gem install rails bundler
# RUN chown -R user:user /opt/app 
WORKDIR /opt/app

# run a shell
CMD ["/bin/sh"]